---

- name: Prepare Statsd directory
  file: state=directory path={{statsd_home}}

- name: Install statsd
  npm: name=statsd path={{statsd_home}}

- name: Install extra NPM dependencies
  npm: name={{item}} path={{statsd_home}}
  with_items: statsd_extra_dependencies

- name: Configure upstart
  template: src=upstart.conf.j2 dest=/etc/init/statsd.conf
  notify:
  - statsd restart

- name: Configure statsd
  template: src=statsd.js.j2 dest={{statsd_home}}/config.js
  notify:
  - statsd restart

- name: Ensure that Statsd is started
  service: name=statsd state=started enabled=yes
